dados     <- read.csv("/home/james/Downloads/saida.txt", header=FALSE , sep=" ")
total <- sum(dados$V1)
dados$V3 <- log2(dados$V1)
x <- seq(1,nrow(dados))
dados <- cbind(dados, x)
dados$V5 <- log2(dados$x)
plot(dados$V3~dados$V5 , pch=22)
lm <- lm(dados$V3~dados$V5)
abline(lm, col="red", lty =1, lwd=2)